Controllers/LogoController.cs
using ComputerClub.Infrastructure;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ComputerClub.Controllers
{
    public class LogoController : ApplicationController
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Edit(int? ClubID)
        {
            if (ClubID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewData["club"] = DataContext.Clubs.Find(ClubID);

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Update")]
        [ValidateAntiForgeryToken]
        public RedirectResult Update(int? ClubID)
        {
            var Context = DataContext;
            var club = Context.Clubs.Find(ClubID);
            var upload = HttpContext.Request.Files[0];
            if (upload.FileName != "")
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                upload.SaveAs(Server.MapPath("~/Content/img/" + fileName));
                var extension = Path.GetExtension(Server.MapPath("~/Content/img/" + fileName)).ToLower();
                ImageFormat imageFormat = ImageFormat.Jpeg;

                switch (extension)
                {
                    case ".jfif": imageFormat = ImageFormat.Jpeg; break;
                    case ".jpg": imageFormat = ImageFormat.Jpeg; break;
                    case ".png": imageFormat = ImageFormat.Png; break;
                    case ".gif": imageFormat = ImageFormat.Gif; break;
                    case ".icon": imageFormat = ImageFormat.Icon; break;
                }

                var PriceImage = ImageLoader.
                    ImageToByteArray(Image.FromFile(Server.MapPath("~/Content/img/" + fileName)), imageFormat);
                var PriceImageMimeType = imageFormat;

                club.LogoImage = PriceImage;
                club.LogoImageMimeType = "image/" + extension.Substring(1);

                Context.SaveChanges();
            }

            return Redirect(Url.Action("Index", "Price"));
        }
    }
}

Views/Logo/Edit.cshtml
@using ComputerClub.Models
@model ComputerClub.Models.Club
@{
    ViewBag.Title = "Edit Logo";
    var club = ViewData["club"] as Club;
}

<section id="genreCreateForm">
    @using (Html.BeginForm("Update", "Logo", new
    {
        ClubID = club.ClubID,
        ReturnUrl = Url.Action("Index", "Logo"),
    },
        FormMethod.Post, new
        {
            @class = "form-horizontal",
            role = "form",
            enctype = "multipart/form-data"
        }))

    {
        <h2>@ViewBag.Title</h2>
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-div">
            <input type="file" name="upload" /><br>
        </div>

        <div class="submit-div">
            <input type="submit" value="Submit" class="mybtn-submit" />
            <a href="@Url.Action("Index", "Logo")" class="mybtn-danger">
                Cancel
            </a>
        </div>
    }
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Logo/Index.cshtml
@{
    ViewBag.Title = "Logo";
}

@{
    var clubs = ViewData["clubs"] as List<ComputerClub.Models.Club>;
    var club = clubs.First();
}

<div class="schedule">
    @Html.Partial("_LeftMenu")
    <div class="img-div">
        <h3>Лого</h3>
        @if (Roles.IsUserInRole("Admin"))
        {
            <div class="add-div">
                <a href='@Url.Action("Edit", "Logo",
               new { ClubID = club.ClubID })'
                   class="mybtn-warning">
                    Редагувати лого
                </a>
            </div>
        }
        <img src='@Url.Action("GetLogoImage", "Club", new { itemId = clubs.First().ClubID })'>
    </div>
</div>